#!/usr/bin/env python3
"""
VK Titan BiS - Data Generator
Reads TBCA_BIS CSV data and generates BiSData.lua for the addon.

Usage:
    1. Download BiS_w_Phase.csv from TBCA_BIS repo
    2. Run: python generate_data.py BiS_w_Phase.csv
    3. Output: BiSData.lua (copy to addon Data/ folder)
"""

import csv
import sys
import os

# Map TBCA_BIS spec abbreviations to our spec keys
# Single mappings (one CSV spec → one addon spec)
SPEC_MAP = {
    "Arms": "WarriorArms",
    "Fury": "WarriorFury",
    "Cat": "DruidCat",
    "Bear": "DruidBear",
    "Tree": "DruidResto",
    "BM": "HunterBM",
    "SV": "HunterSV",
    "Arc": "MageArcane",
    "Fire": "MageFire",
    "Ret": "PaladinRet",
    "Shad": "PriestShadow",
    "Rog": "RogueAssassination",
    "Enh": "ShamanEnhancement",
    "Ele": "ShamanElemental",
    "Aff": "WarlockAffliction",
    "Dest": "WarlockDestruction",
    "Owl": "DruidBalance",
}

# Multi-mappings (one CSV spec → multiple addon specs)
SPEC_MAP_MULTI = {
    "Heal":  ["PaladinHoly", "PriestHoly", "PriestDisc", "DruidResto", "ShamanResto"],
    "Tank":  ["WarriorProt", "DruidBear", "PaladinProt"],
    "Holy":  ["PaladinHoly", "PriestHoly"],
    "Prot":  ["WarriorProt", "PaladinProt"],
    "Resto": ["DruidResto", "ShamanResto"],
}

# Fallback: missing specs use the closest available spec
SPEC_FALLBACK = {
    "HunterMM": "HunterBM",
    "MageFrost": "MageFire",
    "WarlockDemonology": "WarlockAffliction",
    "RogueCombat": "RogueAssassination",
    "RogueSubtlety": "RogueAssassination",
}

# Equipment slot names
SLOT_NAMES = {
    "Head": "Head",
    "Neck": "Neck",
    "Shoulders": "Shoulders",
    "Back": "Back",
    "Chest": "Chest",
    "Wrist": "Wrist",
    "Hands": "Hands",
    "Waist": "Waist",
    "Legs": "Legs",
    "Feet": "Feet",
    "Ring": "Ring",
    "Trinket": "Trinket",
    "Main Hand": "MainHand",
    "Off Hand": "OffHand",
    "Two Hand": "TwoHand",
    "One Hand": "MainHand",
    "Ranged": "Ranged",
    "Relic": "Ranged",
}

# Class definitions
CLASSES = [
    {"key": "DRUID", "name": "Druid", "specs": ["Balance", "Cat", "Bear", "Resto"]},
    {"key": "HUNTER", "name": "Hunter", "specs": ["BM", "MM", "SV"]},
    {"key": "MAGE", "name": "Mage", "specs": ["Arcane", "Fire", "Frost"]},
    {"key": "PALADIN", "name": "Paladin", "specs": ["Holy", "Prot", "Ret"]},
    {"key": "PRIEST", "name": "Priest", "specs": ["Holy", "Disc", "Shadow"]},
    {"key": "ROGUE", "name": "Rogue", "specs": ["Assassination", "Combat", "Subtlety"]},
    {"key": "SHAMAN", "name": "Shaman", "specs": ["Elemental", "Enhancement", "Resto"]},
    {"key": "WARLOCK", "name": "Warlock", "specs": ["Affliction", "Demonology", "Destruction"]},
    {"key": "WARRIOR", "name": "Warrior", "specs": ["Arms", "Fury", "Prot"]},
]


def parse_spec(spec_str, slot):
    """Map TBCA_BIS spec abbreviation to our spec key(s). Returns a list."""
    spec_str = spec_str.strip()

    # Single mapping
    if spec_str in SPEC_MAP:
        return [SPEC_MAP[spec_str]]

    # Multi-mapping (generic specs)
    if spec_str in SPEC_MAP_MULTI:
        return SPEC_MAP_MULTI[spec_str]

    # Unknown spec
    return []


def read_csv(filepath):
    """Read TBCA_BIS CSV and return structured data."""
    data = {}  # spec_key -> phase -> [{slot, itemID, rank}]

    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                item_id = int(row["ItemID"].strip())
            except (ValueError, KeyError):
                continue
            spec = row["Spec"].strip()
            try:
                phase = int(row["GamePhase"].strip())
            except (ValueError, KeyError):
                continue
            slot = row["Slot"].strip()
            try:
                rank = int(row["Rank"].strip())
            except (ValueError, KeyError):
                continue

            if not spec or not slot:
                continue

            spec_keys = parse_spec(spec, slot)
            slot_name = SLOT_NAMES.get(slot, slot)

            for spec_key in spec_keys:
                if spec_key not in data:
                    data[spec_key] = {}
                if phase not in data[spec_key]:
                    data[spec_key][phase] = []

                data[spec_key][phase].append({
                    "slot": slot_name,
                    "itemID": item_id,
                    "rank": rank,
                })

    return data


def generate_lua(data):
    """Generate BiSData.lua content from structured data."""
    lines = [
        "-- VK Titan BiS - Item Rankings",
        "-- AUTO-GENERATED by generate_data.py",
        "-- Do not edit manually!",
        "",
        'local ADDON_NAME, ns = ...',
        "",
        "ns.ClassSpecs = {",
    ]

    for cls in CLASSES:
        specs_str = ", ".join(f'"{s}"' for s in cls["specs"])
        lines.append(f'    {{ key = "{cls["key"]}", name = "{cls["name"]}", specs = {{ {specs_str} }} }},')

    lines.append("}")
    lines.append("")

    # ItemSockets placeholder (would need item database to populate)
    lines.append("-- Socket colors per item (by itemID)")
    lines.append("-- Colors: M=Meta, R=Red, Y=Yellow, B=Blue, P=Prismatic")
    lines.append("-- TODO: Populate from item database or manual curation")
    lines.append("ns.ItemSockets = {}")
    lines.append("")

    # BiS data
    lines.append("ns.BiSData = {}")
    lines.append("")

    for spec_key in sorted(data.keys()):
        lines.append(f'ns.BiSData["{spec_key}"] = {{')
        for phase in sorted(data[spec_key].keys()):
            items = sorted(data[spec_key][phase], key=lambda x: (x["slot"], x["rank"]))
            lines.append(f"    [{phase}] = {{")
            for item in items:
                lines.append(f'        {{ slot = "{item["slot"]}", itemID = {item["itemID"]}, rank = {item["rank"]} }},')
            lines.append("    },")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_data.py <BiS_w_Phase.csv>")
        print("Download CSV from: https://github.com/promexdotme/Best-In-Slot-TBCA-WoW-The-Burning-Crusade-Anniversary")
        sys.exit(1)

    csv_path = sys.argv[1]
    if not os.path.exists(csv_path):
        print(f"Error: File not found: {csv_path}")
        sys.exit(1)

    print(f"Reading {csv_path}...")
    data = read_csv(csv_path)

    # Add fallback data for missing specs
    for missing_spec, fallback_spec in SPEC_FALLBACK.items():
        if missing_spec not in data and fallback_spec in data:
            data[missing_spec] = data[fallback_spec]
            print(f"  {missing_spec} (fallback from {fallback_spec})")

    print(f"\nFound {len(data)} specs:")
    for spec in sorted(data.keys()):
        phases = sorted(data[spec].keys())
        total_items = sum(len(data[spec][p]) for p in phases)
        print(f"  {spec}: {len(phases)} phases, {total_items} items")

    lua_content = generate_lua(data)

    output_path = os.path.join(os.path.dirname(__file__), "..", "Data", "BiSData.lua")
    with open(output_path, "w") as f:
        f.write(lua_content)

    print(f"\nGenerated: {output_path}")
    print("Copy to addon Data/ folder and reload WoW.")


if __name__ == "__main__":
    main()
