#!/usr/bin/env python3
"""
VK Titan BiS - Data Generator
Reads TBCA_BIS CSV data and generates BiSData.lua for the addon.

Usage:
    1. Download BiS_w_Phase.csv from TBCA_BIS repo
    2. Run: python generate_data.py BiS_w_Phase.csv
    3. Output: BiSData.lua (copy to addon Data/ folder)
"""

import csv
import sys
import os

# Map TBCA_BIS spec abbreviations to our spec keys
SPEC_MAP = {
    # Warrior
    "Arms": "WarriorArms",
    "Fury": "WarriorFury",
    "Prot": "WarriorProt",
    # Druid
    "Balance": "DruidBalance",
    "Cat": "DruidCat",
    "Bear": "DruidBear",
    "Tree": "DruidResto",
    "Resto": "DruidResto",
    # Hunter
    "BM": "HunterBM",
    "MM": "HunterMM",
    "SV": "HunterSV",
    # Mage
    "Arc": "MageArcane",
    "Fire": "MageFire",
    "Frost": "MageFrost",
    # Paladin
    "Holy": "PaladinHoly",
    "Ret": "PaladinRet",
    # Priest
    "Shad": "PriestShadow",
    "Disc": "PriestDisc",
    # Rogue
    "Rog": "RogueAssassination",
    # Shaman
    "Enh": "ShamanEnhancement",
    "Ele": "ShamanElemental",
    # Warlock
    "Aff": "WarlockAffliction",
    "Dest": "WarlockDestruction",
}

# Handle ambiguous specs
SPEC_MAP_HOLY_PALADIN = "PaladinHoly"
SPEC_MAP_HOLY_PRIEST = "PriestHoly"
SPEC_MAP_RESTO_SHAMAN = "ShamanResto"
SPEC_MAP_DESTRO = "WarlockDestruction"

# Equipment slot names
SLOT_NAMES = {
    "Head": "Head",
    "Neck": "Neck",
    "Shoulders": "Shoulders",
    "Back": "Back",
    "Chest": "Chest",
    "Wrist": "Wrist",
    "Hands": "Hands",
    "Waist": "Waist",
    "Legs": "Legs",
    "Feet": "Feet",
    "Ring": "Ring",
    "Trinket": "Trinket",
    "Main Hand": "MainHand",
    "Off Hand": "OffHand",
    "Two Hand": "TwoHand",
    "One Hand": "MainHand",
    "Ranged": "Ranged",
    "Relic": "Ranged",
}

# Class definitions
CLASSES = [
    {"key": "DRUID", "name": "Druid", "specs": ["Balance", "Cat", "Bear", "Resto"]},
    {"key": "HUNTER", "name": "Hunter", "specs": ["BM", "MM", "SV"]},
    {"key": "MAGE", "name": "Mage", "specs": ["Arcane", "Fire", "Frost"]},
    {"key": "PALADIN", "name": "Paladin", "specs": ["Holy", "Prot", "Ret"]},
    {"key": "PRIEST", "name": "Priest", "specs": ["Holy", "Disc", "Shadow"]},
    {"key": "ROGUE", "name": "Rogue", "specs": ["Assassination", "Combat", "Subtlety"]},
    {"key": "SHAMAN", "name": "Shaman", "specs": ["Elemental", "Enhancement", "Resto"]},
    {"key": "WARLOCK", "name": "Warlock", "specs": ["Affliction", "Demonology", "Destruction"]},
    {"key": "WARRIOR", "name": "Warrior", "specs": ["Arms", "Fury", "Prot"]},
]


def parse_spec(spec_str, slot):
    """Map TBCA_BIS spec abbreviation to our spec key."""
    spec_str = spec_str.strip()

    # Handle "Holy" for both Paladin and Priest
    if spec_str == "Holy":
        if slot in ("Shield", "Relic") or True:  # Default to Paladin
            return "PaladinHoly"
        return "PriestHoly"

    # Handle "Resto" for Druid, Shaman
    if spec_str == "Resto":
        return "ShamanResto"

    # Handle "Dest" for Warlock
    if spec_str == "Dest":
        return "WarlockDestruction"

    return SPEC_MAP.get(spec_str, spec_str)


def read_csv(filepath):
    """Read TBCA_BIS CSV and return structured data."""
    data = {}  # spec_key -> phase -> [{slot, itemID, rank}]

    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            item_id = int(row["ItemID"])
            spec = row["Spec"].strip()
            phase = int(row["GamePhase"])
            slot = row["Slot"].strip()
            rank = int(row["Rank"])

            spec_key = parse_spec(spec, slot)
            slot_name = SLOT_NAMES.get(slot, slot)

            if spec_key not in data:
                data[spec_key] = {}
            if phase not in data[spec_key]:
                data[spec_key][phase] = []

            data[spec_key][phase].append({
                "slot": slot_name,
                "itemID": item_id,
                "rank": rank,
            })

    return data


def generate_lua(data):
    """Generate BiSData.lua content from structured data."""
    lines = [
        "-- VK Titan BiS - Item Rankings",
        "-- AUTO-GENERATED by generate_data.py",
        "-- Do not edit manually!",
        "",
        'local ADDON_NAME, ns = ...',
        "",
        "ns.ClassSpecs = {",
    ]

    for cls in CLASSES:
        specs_str = ", ".join(f'"{s}"' for s in cls["specs"])
        lines.append(f'    {{ key = "{cls["key"]}", name = "{cls["name"]}", specs = {{ {specs_str} }} }},')

    lines.append("}")
    lines.append("")

    # ItemSockets placeholder (would need item database to populate)
    lines.append("-- Socket colors per item (by itemID)")
    lines.append("-- Colors: M=Meta, R=Red, Y=Yellow, B=Blue, P=Prismatic")
    lines.append("-- TODO: Populate from item database or manual curation")
    lines.append("ns.ItemSockets = {}")
    lines.append("")

    # BiS data
    lines.append("ns.BiSData = {}")
    lines.append("")

    for spec_key in sorted(data.keys()):
        lines.append(f'ns.BiSData["{spec_key}"] = {{')
        for phase in sorted(data[spec_key].keys()):
            items = sorted(data[spec_key][phase], key=lambda x: (x["slot"], x["rank"]))
            lines.append(f"    [{phase}] = {{")
            for item in items:
                lines.append(f'        {{ slot = "{item["slot"]}", itemID = {item["itemID"]}, rank = {item["rank"]} }},')
            lines.append("    },")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_data.py <BiS_w_Phase.csv>")
        print("Download CSV from: https://github.com/promexdotme/Best-In-Slot-TBCA-WoW-The-Burning-Crusade-Anniversary")
        sys.exit(1)

    csv_path = sys.argv[1]
    if not os.path.exists(csv_path):
        print(f"Error: File not found: {csv_path}")
        sys.exit(1)

    print(f"Reading {csv_path}...")
    data = read_csv(csv_path)

    print(f"Found {len(data)} specs:")
    for spec in sorted(data.keys()):
        phases = sorted(data[spec].keys())
        total_items = sum(len(data[spec][p]) for p in phases)
        print(f"  {spec}: {len(phases)} phases, {total_items} items")

    lua_content = generate_lua(data)

    output_path = os.path.join(os.path.dirname(__file__), "..", "Data", "BiSData.lua")
    with open(output_path, "w") as f:
        f.write(lua_content)

    print(f"\nGenerated: {output_path}")
    print("Copy to addon Data/ folder and reload WoW.")


if __name__ == "__main__":
    main()
